#Postgres Database
spring.datasource.url=jdbc:postgresql://localhost:5433/libraryDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Book
book.properties.borrowedAtSize=15
book.properties.borrowedEndSize=15

#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_MAIL:dev.pb.emailtest@gmail.com}
spring.mail.password=${USER_PASSWORD_MAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.debug=true


