#H2 Database
spring.datasource.url=jdbc:h2:file:${user.home}/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#SQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Book
book.properties.borrowedAtSize=15
book.properties.borrowedEndSize=15

#Mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev.pb.emailtest@gmail.com
spring.mail.password=Dev.pb.emailT
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.debug=true


