#H2 Database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#SQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Book
book.properties.borrowedAtSize=15
book.properties.borrowedEndSize=15

#Mail

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=dev.pb.example@gmail.com
spring.mail.password=dev.pb.example@gmail.com


spring.properties.mail.smtp.ssl.trust="*"
spring.properties.mail.smtp.auth=true
spring.properties.mail.smtp.starttls.enable=true
spring.properties.mail.smtp.connectiontimeout=5000
spring.properties.mail.smtp.timeout=3000
spring.properties.mail.smtp.writetimeout=5000